/**
 * barrel 文件：物理拆分后仅做转发，导出集合与拆分前完全一致。
 * 各职责域拆分到 weak-signals/ 子目录（types/detection/projection/strategy）。
 */
export {
  SLOW_RECALL_MS,
  LOOKUP_WEAK_THRESHOLD,
  LOOKUP_PRIORITY_THRESHOLD,
  STUBBORN_SPRINT_SESSION_PREFIX,
  TREATMENT_SPRINT_SESSION_PREFIX,
  createStubbornSprintSessionId,
  createTreatmentSprintSessionId,
  parseSprintSessionId,
  parseStubbornSprintSessionId,
  wordRecallStats,
  lookupStatForWordId,
  deriveLeechDerivation,
  upsertLeechMute,
  pruneExpiredLeechMutes,
  buildWordWeakSignalEntries,
  buildWordWeakSignals,
  buildWeakProfiles,
  buildWeakConcentration,
  lookupWeakCandidateIds,
  buildWeakCandidateSummary,
  isLookupDemoted,
  buildWordStabilizedDimensions,
  isLookupStabilized,
} from "./weak-signals/detection.ts";

export {
  DEFAULT_WEAK_THRESHOLDS,
  type WeakThresholds,
} from "./study.ts";

export {
  STUBBORN_TREATMENT_SEQUENCE,
  SPRINT_TREATMENT_DIMENSIONS,
  type DimensionObservationReport,
  type DimensionObservationRow,
  type PairedRecallChange,
  type ParsedSprintSession,
  type SprintEffectiveness,
  type SprintEffectivenessWeek,
  type SprintHistory,
  type SprintHistoryRecord,
  type SprintRelapse,
  type SprintRelapseWeek,
  type SprintRetention,
  type SprintRetentionPairedRecall,
  type SprintRetentionWeek,
  type SprintScope,
  type SprintTreatmentDimension,
  type SprintTreatmentRecommendation,
  type StabilizedDimension,
  type StubbornTreatmentMode,
  type WeakDimensionTrend,
  type WeakDimensionTrendWeek,
  type WeakSectionConcentration,
  type WeakSignalEntry,
  type WeakSignalInput,
  type WeakSignalKey,
  type WeakUnitConcentration,
  type WeakWordProfile,
  type WordRecallStats,
  type WordSignalEvent,
  type LeechDerivation,
  type LeechMuteRecord,
  type LeechTier,
} from "./weak-signals/types.ts";

export {
  buildSprintHistory,
  buildSprintRecordWordIds,
  buildPairedRecallChange,
  buildSprintEffectiveness,
  buildSprintEffectivenessSeries,
  buildSprintRelapse,
  buildSprintRelapseSeries,
  buildSprintRetentionSeries,
  buildDimensionObservationReport,
  buildWordSignalTimeline,
  lookupPriorityWordIds,
  emphasizedWeakDimensions,
  buildWeakDimensionTrend,
  buildWeakDimensionTrendSeries,
} from "./weak-signals/projection.ts";

export {
  buildSprintWordIds,
  buildStubbornTreatmentRecommendation,
  buildSprintTreatmentRecommendation,
  buildScopedSprintWordIds,
  buildSprintSummary,
  buildSprintCsv,
} from "./weak-signals/strategy.ts";
